### ISSUE TITLE
Missing double quote

### ISSUE THREAD

**Issue by mhightower** [reload/phing-drupal-template#17]
The build.xml has a missing double quote in master at line 254 that caused a problem for me. Looks fixed in develop.
Last touched in commit:
066b43f - Pol Dell'Aiera Pol@47194.no-reply.drupal.org Apr 10, 2012
Support HTTPGET proxy.

**Comment by drupol** [comment]
??

**Comment by kasperg** [comment]
You are correct @mhightower. Thanks for reporting this issue.

The syntax errors were introduced in `master` and have been fixed here at well - see 6f1d3bc551d56a6fd190ca9491ebefbb1cd69d40. 

The versioning/branching is not optimal at the moment. I wanted to introduce git-flow but then development slowed down and pull requests have since been accepted directly into the master branch.
