### ISSUE TITLE
Jenkins cannot create new folders for some reason

### ISSUE THREAD

**Issue by humansky** [reload/phing-drupal-template#28]
Getting a strange error on my Jenkins server and I can't seem to pinpoint the exact reason.

```
phing-drupal > setup-git-repo:

     [echo] Cloning https://github.com/kasperg/phing-drush-task.git HEAD into /var/lib/jenkins/jobs/DCNJ CI Demo/workspace/build/build/tools/phing-drush
       [if] Error in IfTask
Execution of target "setup-git-repo" failed for the following reason: /var/lib/jenkins/jobs/DCNJ CI Demo/workspace/build/build.xml:1181:4: /var/lib/jenkins/jobs/DCNJ CI Demo/workspace/build/build.xml:1183:6: '/var/lib/jenkins/jobs/DCNJ CI Demo/workspace/build/build/tools/phing-drush' is not a valid directory
[phingcall] /var/lib/jenkins/jobs/DCNJ CI Demo/workspace/build/build.xml:1181:4: /var/lib/jenkins/jobs/DCNJ CI Demo/workspace/build/build.xml:1183:6: '/var/lib/jenkins/jobs/DCNJ CI Demo/workspace/build/build/tools/phing-drush' is not a valid directory
Execution of target "setup-phing-drush" failed for the following reason: /var/lib/jenkins/jobs/DCNJ CI Demo/workspace/build/build.xml:1220:18: Execution of the target buildfile failed. Aborting.

BUILD FAILED
/var/lib/jenkins/jobs/DCNJ CI Demo/workspace/build/build.xml:1220:18: Execution of the target buildfile failed. Aborting.
Total time: 0.1351 seconds

Build step 'Invoke Phing targets' marked build as failure
[CHECKSTYLE] Skipping publisher since build result is FAILURE
[PMD] Skipping publisher since build result is FAILURE
[DRY] Skipping publisher since build result is FAILURE
[ANALYSIS-COLLECTOR] Skipping publisher since build result is FAILURE
Recording plot data
Recording test results
Finished: FAILURE
```

I'm using your unmodified Phing configuration file. Any thought on why Jenkins cannot create the tools folder? I'm new to Phong, so let me know if you need anymore info.

**Comment by xendk** [comment]
Tried without spaces in the job name?

**Comment by humansky** [comment]
That was it....you'd think Jenkins would be able to handle spaces in job names. I wonder if it's a bug in Phing. Thank you!!!

**Comment by san1411** [comment]
uilding in workspace /var/lib/jenkins/workspace/Jenkins_test
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/marcelog/Ci-Php-phing-Example # timeout=10
Fetching upstream changes from https://github.com/marcelog/Ci-Php-phing-Example
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/marcelog/Ci-Php-phing-Example +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 81e1593e51f0dba2e0144385dbb7cf61aaea2e50 (refs/remotes/origin/master)
Commit message: "set standard default location for php in php.properties.example"
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 81e1593e51f0dba2e0144385dbb7cf61aaea2e50
 > git rev-list 81e1593e51f0dba2e0144385dbb7cf61aaea2e50 # timeout=10
looking for '/var/lib/jenkins/workspace/Jenkins_test' ... 
use '/var/lib/jenkins/workspace' as a working directory. 
[workspace] $ phing -buildfile /var/lib/jenkins/workspace/Jenkins_test clean install-dependencies all -logger phing.listener.DefaultLogger version=${APP_VERSION} commit=81e1593e51f0dba2e0144385dbb7cf61aaea2e50
Buildfile: /var/lib/jenkins/workspace/Jenkins_test is a dir!
Build step 'Invoke Phing targets' marked build as failure
[CHECKSTYLE] Skipping publisher since build result is FAILURE
[PMD] Skipping publisher since build result is FAILURE
[DRY] Skipping publisher since build result is FAILURE
[htmlpublisher] Archiving HTML reports...
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: Test reports were found but none of them are new. Did tests run? 
For example, /var/lib/jenkins/workspace/Jenkins_test/README is 6 days 13 hr old

[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] Skipped based on build state FAILURE
Finished: FAILURE

**Comment by san1411** [comment]
Can anyone help me

**Comment by gofunbox** [comment]
-buildfile  /var/lib/jenkins/workspace/Jenkins_test  must be file
